//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class KasperskyTowerAI : TowerAI
	{
		public KasperskyTowerAI ()
		{
			towerDamage = 10;
			attackSpd = 1.5f;
			attacksGround = true;
			attacksAir = false;
			revealsInvisible = true;
			attackRange = 1.0f;
			drainDamage = 20;
			drainSpd = 0.8f;
			drainDuration = 2.0f;
		}

		// Update is called once per frame
		void Update()
		{
			towerAI();
		}
		
		public override void shootTarget(GameObject target)
		{
			base.shootTarget(target);
		}
	}
}

