//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class McAfeeTowerAI : TowerAI
	{
		public McAfeeTowerAI() : base()
		{
			towerDamage = 50;
			attackSpd = 0.5f;
			attacksGround = true;
			attacksAir = false;
			drainDamage = 20;
			drainSpd = 0.8f;
			drainDuration = 2.0f;
		}
	}
}

