//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDefenderWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreadPost
    {
        public int PostId { get; set; }
        public int ThreadId { get; set; }
        public string UserId { get; set; }
        public string Post { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Thread Thread { get; set; }
    }
}
