//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDefenderWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Virus
    {
        public int VirusId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Speed { get; set; }
        public int Armour { get; set; }
        public int Resistance { get; set; }
        public int Health { get; set; }
        public Nullable<int> SpAbilityId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual SpecialAbility SpecialAbility { get; set; }
    }
}
