//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDefender_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public string UserId { get; set; }
        public string FriendId { get; set; }
        public System.DateTime DateFriended { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
