//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDefender_WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int MapId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DifficultyRating { get; set; }
        public string ImageUrl { get; set; }
    }
}
