//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDefender_WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TowerDefenceEntities : DbContext
    {
        public TowerDefenceEntities()
            : base("name=TowerDefenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<MatchHistory> MatchHistories { get; set; }
        public virtual DbSet<MatchHistoryDetail> MatchHistoryDetails { get; set; }
        public virtual DbSet<SpecialAbility> SpecialAbilities { get; set; }
        public virtual DbSet<ThreadPost> ThreadPosts { get; set; }
        public virtual DbSet<Thread> Threads { get; set; }
        public virtual DbSet<Tower> Towers { get; set; }
        public virtual DbSet<Virus> Viruses { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
    }
}
